### ISSUE TITLE
Remove copy constructor and add_all() in array.h

### ISSUE THREAD

**Issue by chasebish** [rucha2398/cs4500-a1-p2#22]
I think there might have been a misunderstanding on the previous issue. I don't want the copy constructor removed from the sub-classes, only `array.h`. As I said on issue #17 there is no reason to copy an Object as they have no real value associated with them besides their space in memory. Copying of array elements will be handled specifically in their sub-classes.

This applies to add_all as well because copies are required to be made in order to properly add the elements from one array to another so that they can be properly freed. Again, I would only like it removed from `array.h`.

**Comment by chasebish** [comment]
I guess this brings up a different question depending on how you want this resolved. When it comes to copying/combining arrays, should a new pointer be created for Objects/Strings?

If a new pointer should be created (which is how I implemented it), then there is no reason to copy Objects since having a copy refer to the same space in memory would cause issues. Additionally, some changes would need to be made to the StringArray->add_all() test since some elements are not being freed correctly.

If a new pointer should not be created and we should just add the same pointer to the array, then nothing needs to be changed I can implement it as so, but this could be dangerous as editing an Object or a String in one Array will change the value inside the other Array as well.

**Comment by rucha2398** [comment]
Since the pointers in the Array are not owned, we assumed that the pointers themselves would be copied. It is true that changing the value of a copied object will change it in both arrays. However, changing the pointers in the array will not influence the copy since they have separate memory. If the user truly wants a deep copy of the elements, they will have to do that themselves.
We can change the comments on the copy constructor and add_all to reflect the desired behavior.
